# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

##### Assignment 1

In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
### Assignment 1
arr=np.random.randint(1,20,(5,5))
arr

array([[ 7, 15, 11,  8,  7],
       [19, 11, 11,  4,  8],
       [ 3,  2, 12,  6,  2],
       [ 1, 12, 12, 17, 10],
       [16, 15, 15, 19, 12]])

In [5]:
arr[:,2]=1
arr

array([[ 7, 15,  1,  8,  7],
       [19, 11,  1,  4,  8],
       [ 3,  2,  1,  6,  2],
       [ 1, 12,  1, 17, 10],
       [16, 15,  1, 19, 12]])

In [6]:
arr=np.random.randint(1,16,(4,4))
arr

array([[ 7,  4,  9,  3],
       [ 5,  3,  7,  5],
       [ 9,  7,  2,  4],
       [ 9, 12, 14,  2]])

In [7]:
np.fill_diagonal(arr,0)
arr

array([[ 0,  4,  9,  3],
       [ 5,  0,  7,  5],
       [ 9,  7,  0,  4],
       [ 9, 12, 14,  0]])

#### Assignment 2

In [8]:
arr=np.arange(1,37).reshape((6,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
arr[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [10]:
arr=np.random.randn(5,5)
arr

array([[-0.1402185 , -0.0331934 , -0.74907652, -0.77838201,  0.94884286],
       [ 1.58085059, -0.36817094,  0.37556463, -1.19315823, -0.4090519 ],
       [-0.44674147,  1.52424163,  0.3229998 , -1.39341694, -2.17833425],
       [-1.04389641,  0.17269371,  0.32419877,  0.74585954, -1.83658324],
       [ 0.56446424,  0.02550067,  0.47319325,  0.6591906 ,  2.34074633]])

In [11]:
edges=np.concatenate([arr[0,:],arr[:,0],arr[-1,:],arr[:,-1]])
edges

array([-0.1402185 , -0.0331934 , -0.74907652, -0.77838201,  0.94884286,
       -0.1402185 ,  1.58085059, -0.44674147, -1.04389641,  0.56446424,
        0.56446424,  0.02550067,  0.47319325,  0.6591906 ,  2.34074633,
        0.94884286, -0.4090519 , -2.17833425, -1.83658324,  2.34074633])

#### Assignment 3

In [12]:
arr1=np.random.rand(3,4)
arr2=np.random.rand(3,4)
arr1,arr2

(array([[0.96525531, 0.60703425, 0.27599918, 0.29627351],
        [0.16526694, 0.01563641, 0.42340148, 0.39488152],
        [0.29348817, 0.01407982, 0.1988424 , 0.71134195]]),
 array([[0.79017554, 0.60595997, 0.92630088, 0.65107703],
        [0.91495968, 0.85003858, 0.44945067, 0.09541012],
        [0.37081825, 0.66884125, 0.66592236, 0.59129779]]))

In [13]:
arr1+arr2

array([[1.75543085, 1.21299422, 1.20230006, 0.94735053],
       [1.08022661, 0.86567498, 0.87285215, 0.49029163],
       [0.66430643, 0.68292108, 0.86476476, 1.30263974]])

In [14]:
arr1-arr2

array([[ 0.17507977,  0.00107427, -0.6503017 , -0.35480352],
       [-0.74969274, -0.83440217, -0.02604919,  0.2994714 ],
       [-0.07733008, -0.65476143, -0.46707995,  0.12004417]])

In [15]:
arr1*arr2

array([[0.76272113, 0.36783846, 0.25565828, 0.19289687],
       [0.15121258, 0.01329155, 0.19029808, 0.03767569],
       [0.10883077, 0.00941717, 0.1324136 , 0.42061492]])

In [16]:
arr1/arr2

array([[1.22157072, 1.00177284, 0.29795846, 0.45505139],
       [0.18062757, 0.01839494, 0.94204215, 4.13878038],
       [0.79146097, 0.02105107, 0.29859698, 1.20301812]])

In [17]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
np.sum(arr,axis=0)

array([28, 32, 36, 40])

In [19]:
np.sum(arr,axis=1)

array([10, 26, 42, 58])

#### Assignment 4

Q1

In [24]:
arr=np.random.randint(0,1000,size=(5,5))
arr

array([[899, 733, 484, 406, 230],
       [748, 654, 170, 540,  35],
       [524, 159, 838, 698, 242],
       [ 85, 795, 577, 681, 556],
       [573, 952, 645, 795,  27]])

In [25]:
mean=np.mean(arr)
std_deviation=np.std(arr)
variance=np.var(arr)
print(f"Mean of the array:{mean}\nStandard deviation of the array:{std_deviation}\nVariance of the array:{variance}")

Mean of the array:521.84
Standard deviation of the array:273.8510076665777
Variance of the array:74994.3744


Q2

In [33]:
arr=np.arange(1,10,dtype=np.float64).reshape(3,3)
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [34]:
mean=np.mean(arr)
std=np.std(arr)
arr-=np.mean(arr)
arr

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [36]:
arr/=std
arr

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [37]:
print(f"New mean of array:{np.mean(arr)} and standard deviation:{np.std(arr)}")

New mean of array:0.0 and standard deviation:1.0


#### Assignment 5

Q1