# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
import numpy as np
np.random.seed(42)

##### Assignment 1

In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
### Assignment 1
arr=np.random.randint(1,20,(5,5))
arr

array([[ 7, 15, 11,  8,  7],
       [19, 11, 11,  4,  8],
       [ 3,  2, 12,  6,  2],
       [ 1, 12, 12, 17, 10],
       [16, 15, 15, 19, 12]])

In [5]:
arr[:,2]=1
arr

array([[ 7, 15,  1,  8,  7],
       [19, 11,  1,  4,  8],
       [ 3,  2,  1,  6,  2],
       [ 1, 12,  1, 17, 10],
       [16, 15,  1, 19, 12]])

In [6]:
arr=np.random.randint(1,16,(4,4))
arr

array([[ 7,  4,  9,  3],
       [ 5,  3,  7,  5],
       [ 9,  7,  2,  4],
       [ 9, 12, 14,  2]])

In [7]:
np.fill_diagonal(arr,0)
arr

array([[ 0,  4,  9,  3],
       [ 5,  0,  7,  5],
       [ 9,  7,  0,  4],
       [ 9, 12, 14,  0]])

#### Assignment 2

In [8]:
arr=np.arange(1,37).reshape((6,6))
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [9]:
arr[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [10]:
arr=np.random.randn(5,5)
arr

array([[-0.1402185 , -0.0331934 , -0.74907652, -0.77838201,  0.94884286],
       [ 1.58085059, -0.36817094,  0.37556463, -1.19315823, -0.4090519 ],
       [-0.44674147,  1.52424163,  0.3229998 , -1.39341694, -2.17833425],
       [-1.04389641,  0.17269371,  0.32419877,  0.74585954, -1.83658324],
       [ 0.56446424,  0.02550067,  0.47319325,  0.6591906 ,  2.34074633]])

In [11]:
edges=np.concatenate([arr[0,:],arr[:,0],arr[-1,:],arr[:,-1]])
edges

array([-0.1402185 , -0.0331934 , -0.74907652, -0.77838201,  0.94884286,
       -0.1402185 ,  1.58085059, -0.44674147, -1.04389641,  0.56446424,
        0.56446424,  0.02550067,  0.47319325,  0.6591906 ,  2.34074633,
        0.94884286, -0.4090519 , -2.17833425, -1.83658324,  2.34074633])

#### Assignment 3

In [12]:
arr1=np.random.rand(3,4)
arr2=np.random.rand(3,4)
arr1,arr2

(array([[0.96525531, 0.60703425, 0.27599918, 0.29627351],
        [0.16526694, 0.01563641, 0.42340148, 0.39488152],
        [0.29348817, 0.01407982, 0.1988424 , 0.71134195]]),
 array([[0.79017554, 0.60595997, 0.92630088, 0.65107703],
        [0.91495968, 0.85003858, 0.44945067, 0.09541012],
        [0.37081825, 0.66884125, 0.66592236, 0.59129779]]))

In [13]:
arr1+arr2

array([[1.75543085, 1.21299422, 1.20230006, 0.94735053],
       [1.08022661, 0.86567498, 0.87285215, 0.49029163],
       [0.66430643, 0.68292108, 0.86476476, 1.30263974]])

In [14]:
arr1-arr2

array([[ 0.17507977,  0.00107427, -0.6503017 , -0.35480352],
       [-0.74969274, -0.83440217, -0.02604919,  0.2994714 ],
       [-0.07733008, -0.65476143, -0.46707995,  0.12004417]])

In [15]:
arr1*arr2

array([[0.76272113, 0.36783846, 0.25565828, 0.19289687],
       [0.15121258, 0.01329155, 0.19029808, 0.03767569],
       [0.10883077, 0.00941717, 0.1324136 , 0.42061492]])

In [16]:
arr1/arr2

array([[1.22157072, 1.00177284, 0.29795846, 0.45505139],
       [0.18062757, 0.01839494, 0.94204215, 4.13878038],
       [0.79146097, 0.02105107, 0.29859698, 1.20301812]])

In [17]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
np.sum(arr,axis=0)

array([28, 32, 36, 40])

In [19]:
np.sum(arr,axis=1)

array([10, 26, 42, 58])

#### Assignment 4

Q1

In [24]:
arr=np.random.randint(0,1000,size=(5,5))
arr

array([[899, 733, 484, 406, 230],
       [748, 654, 170, 540,  35],
       [524, 159, 838, 698, 242],
       [ 85, 795, 577, 681, 556],
       [573, 952, 645, 795,  27]])

In [25]:
mean=np.mean(arr)
std_deviation=np.std(arr)
variance=np.var(arr)
print(f"Mean of the array:{mean}\nStandard deviation of the array:{std_deviation}\nVariance of the array:{variance}")

Mean of the array:521.84
Standard deviation of the array:273.8510076665777
Variance of the array:74994.3744


Q2

In [33]:
arr=np.arange(1,10,dtype=np.float64).reshape(3,3)
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [34]:
mean=np.mean(arr)
std=np.std(arr)
arr-=np.mean(arr)
arr

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [36]:
arr/=std
arr

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [37]:
print(f"New mean of array:{np.mean(arr)} and standard deviation:{np.std(arr)}")

New mean of array:0.0 and standard deviation:1.0


#### Assignment 5

Q1

In [17]:
arr=np.random.rand(3,3)
oned_arr=np.random.rand(3,)
print(arr)
print(oned_arr)

[[0.63755747 0.88721274 0.47221493]
 [0.11959425 0.71324479 0.76078505]
 [0.5612772  0.77096718 0.4937956 ]]
[0.52273283 0.42754102 0.02541913]


In [18]:
summed_arr=arr+oned_arr
summed_arr

array([[1.1602903 , 1.31475376, 0.49763405],
       [0.64232708, 1.14078581, 0.78620418],
       [1.08401003, 1.1985082 , 0.51921472]])

In [7]:
assert summed_arr[0][0]==arr[0][0]+oned_arr[0]
assert summed_arr[0][1]==arr[0][1]+oned_arr[1]
assert summed_arr[0][2]==arr[0][2]+oned_arr[2]
assert summed_arr[1][0]==arr[1][0]+oned_arr[0]
assert summed_arr[1][1]==arr[1][1]+oned_arr[1]
assert summed_arr[1][2]==arr[1][2]+oned_arr[2]
assert summed_arr[2][0]==arr[2][0]+oned_arr[0]
assert summed_arr[2][1]==arr[2][1]+oned_arr[1]
assert summed_arr[2][2]==arr[2][2]+oned_arr[2]

Q2

In [43]:
arr=np.random.randint(0,10,(4,4))
col_arr=np.random.rand(4,1)
print(arr)
print(col_arr)

[[7 3 0 7]
 [3 5 7 3]
 [2 8 2 8]
 [1 1 1 5]]
[[0.44842414]
 [0.99445746]
 [0.17592525]
 [0.01807536]]


In [44]:
diff_arr=arr-col_arr

In [46]:
diff_arr

array([[ 6.55157586,  2.55157586, -0.44842414,  6.55157586],
       [ 2.00554254,  4.00554254,  6.00554254,  2.00554254],
       [ 1.82407475,  7.82407475,  1.82407475,  7.82407475],
       [ 0.98192464,  0.98192464,  0.98192464,  4.98192464]])

In [48]:
assert diff_arr[0][0]==arr[0][0]-col_arr[0][0]
assert diff_arr[0][1]==arr[0][1]-col_arr[0][0]
assert diff_arr[0][2]==arr[0][2]-col_arr[0][0]
assert diff_arr[0][3]==arr[0][3]-col_arr[0][0]
assert diff_arr[1][0]==arr[1][0]-col_arr[1][0]
assert diff_arr[1][1]==arr[1][1]-col_arr[1][0]
assert diff_arr[1][2]==arr[1][2]-col_arr[1][0]
assert diff_arr[1][3]==arr[1][3]-col_arr[1][0]
assert diff_arr[2][0]==arr[2][0]-col_arr[2][0]
assert diff_arr[2][1]==arr[2][1]-col_arr[2][0]
assert diff_arr[2][2]==arr[2][2]-col_arr[2][0]
assert diff_arr[2][3]==arr[2][3]-col_arr[2][0]
assert diff_arr[3][0]==arr[3][0]-col_arr[3][0]
assert diff_arr[3][1]==arr[3][1]-col_arr[3][0]
assert diff_arr[3][2]==arr[3][2]-col_arr[3][0]
assert diff_arr[3][3]==arr[3][3]-col_arr[3][0]

#### Assignment 6

Q1

In [5]:
arr=np.random.randint(1,11,size=(3,3))
det=np.linalg.det(arr)
inverse=np.linalg.inv(arr)
eigen=np.linalg.eigvals(arr)
print(arr)
print(f"Inverse: {inverse}\nDeterminant:{det}\nEigenValue:{eigen}")

[[5 4 8]
 [8 3 6]
 [5 2 8]]
Inverse: [[-0.17647059  0.23529412  0.        ]
 [ 0.5         0.         -0.5       ]
 [-0.01470588 -0.14705882  0.25      ]]
Determinant:-68.00000000000001
EigenValue:[16.04752044 -2.08239552  2.03487508]


Q2

In [7]:
arr1=np.random.randint(1,11,(3,2))
arr2=np.random.randint(1,11,(2,3))

print(arr1,arr2,sep="\n")

res=np.matmul(arr1,arr2)
print(res)

[[9 3]
 [5 3]
 [7 5]]
[[9 7 2]
 [4 9 2]]
[[93 90 24]
 [57 62 16]
 [83 94 24]]


#### Assignement 7

Q1

In [12]:
arr=np.arange(1,10).reshape((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr=arr.reshape((1,9))
print(arr)

[[1 2 3 4 5 6 7 8 9]]


In [14]:
arr=arr.reshape((9,1))
print(arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


Q2

In [15]:
arr=np.random.randint(0,15,size=(5,5))
print(arr)

[[ 9  8  9  4  1]
 [ 3 11 14 11  6]
 [11 12  7 14  2]
 [13  0  3  1  7]
 [ 3  1 13  5  5]]


In [16]:
arr=arr.flatten()
print(arr)

[ 9  8  9  4  1  3 11 14 11  6 11 12  7 14  2 13  0  3  1  7  3  1 13  5
  5]


In [17]:
arr=arr.reshape((5,5))
print(arr)

[[ 9  8  9  4  1]
 [ 3 11 14 11  6]
 [11 12  7 14  2]
 [13  0  3  1  7]
 [ 3  1 13  5  5]]


#### Assignment 8

Q1

In [18]:
arr=np.random.randint(0,25,(5,5))
print(arr)

[[ 9  3 21 17 11]
 [ 1  9  3 13 15]
 [14  7 13 22 24]
 [ 7 20 15 12 17]
 [14 20 23 24 12]]


In [19]:
corners=arr[[0,0,-1,-1],[0,-1,0,-1]]
print(corners)

[ 9 11 14 12]


Q2

In [20]:
arr=np.random.randint(0,25,(4,4))
print(arr)

[[ 8 14 12  0]
 [24  6  8 23]
 [ 0 11  7 23]
 [10 18 16  7]]


In [21]:
arr[arr>10]=10
print(arr)

[[ 8 10 10  0]
 [10  6  8 10]
 [ 0 10  7 10]
 [10 10 10  7]]


#### Assignment 9

Q1

In [25]:
data_type=[('Name','U14'),('Age','i4'),('Weight','f4')]
structured_arr=np.array([('Alice',25,56),('Bob',23,88),('Charles',35,78),('Dereck',32,78),('Emsbry',21,77)],dtype=data_type)
print(structured_arr)

[('Alice', 25, 56.) ('Bob', 23, 88.) ('Charles', 35, 78.)
 ('Dereck', 32, 78.) ('Emsbry', 21, 77.)]


In [26]:
sorted_arr=np.sort(structured_arr,order='Age')
print(sorted_arr)

[('Emsbry', 21, 77.) ('Bob', 23, 88.) ('Alice', 25, 56.)
 ('Dereck', 32, 78.) ('Charles', 35, 78.)]


Q2

In [36]:
data_type=[('x','i4'),('y','i4')]
points=np.array([(2,5),(4,7),(3,13),(5,7),(2,6),(4,9),(8,2),(7,3),(9,9),(9,1),(10,13),(8,4)],dtype=data_type)
print(points)
print(points.shape)

[( 2,  5) ( 4,  7) ( 3, 13) ( 5,  7) ( 2,  6) ( 4,  9) ( 8,  2) ( 7,  3)
 ( 9,  9) ( 9,  1) (10, 13) ( 8,  4)]
(12,)


In [40]:
print(np.sqrt((points['x'][:,np.newaxis]-points['x'])**2+(points['y'][np.newaxis,:]-points['y'])**2))

[[0. 2. 1. 3. 0. 2. 6. 5. 7. 7. 8. 6.]
 [2. 0. 1. 1. 2. 0. 4. 3. 5. 5. 6. 4.]
 [1. 1. 0. 2. 1. 1. 5. 4. 6. 6. 7. 5.]
 [3. 1. 2. 0. 3. 1. 3. 2. 4. 4. 5. 3.]
 [0. 2. 1. 3. 0. 2. 6. 5. 7. 7. 8. 6.]
 [2. 0. 1. 1. 2. 0. 4. 3. 5. 5. 6. 4.]
 [6. 4. 5. 3. 6. 4. 0. 1. 1. 1. 2. 0.]
 [5. 3. 4. 2. 5. 3. 1. 0. 2. 2. 3. 1.]
 [7. 5. 6. 4. 7. 5. 1. 2. 0. 0. 1. 1.]
 [7. 5. 6. 4. 7. 5. 1. 2. 0. 0. 1. 1.]
 [8. 6. 7. 5. 8. 6. 2. 3. 1. 1. 0. 2.]
 [6. 4. 5. 3. 6. 4. 0. 1. 1. 1. 2. 0.]]


#### Assignment 10

Q1

In [41]:
arr=np.random.randint(1,25,size=(4,4))
print(arr)

[[ 3  3  1  5]
 [10  7  9  7]
 [ 9  8 12  2]
 [ 1 16 23 23]]


In [42]:
mask=arr>10
print(mask)

[[False False False False]
 [False False False False]
 [False False  True False]
 [False  True  True  True]]


In [43]:
masked_arr=arr[mask]

In [44]:
masked_arr

array([12, 16, 23, 23])

In [46]:
print(masked_arr.sum())

74


Q2

In [47]:
arr=np.random.randint(1,15,size=(3,3))
print(arr)

[[14  8  5]
 [ 3 12  8]
 [ 6 11  3]]


In [49]:
mask=np.diag(arr)
print(mask)
other_elements=arr[arr!=mask]
print(other_elements)

[14 12  3]
[ 8  5  3  8  6 11]


In [50]:
mean_other_ele=other_elements.mean()
print(mean_other_ele)
arr[arr==mask]=mean_other_ele
print(arr)

6.833333333333333
[[ 6  8  5]
 [ 3  6  8]
 [ 6 11  6]]
