Q1: Import numpy as np and see the version

In [2]:
import numpy as np
np.__version__

'1.26.4'

Q2: create a 1D array of numbers from 0 to 9

In [4]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q3: Create a 3×3 numpy array of all True’s

In [5]:
all_trues=np.ones((3,3))
all_trues

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Q4: Extract all odd numbers from arr

Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_=np.array([0,1,2,3,4,5,6,7,8,9])
arr_[arr_%2==1]

array([1, 3, 5, 7, 9])

Q5. Replace all odd numbers in arr with -1

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

Output:

`array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])`

In [9]:
q5_arr=np.array([0,1,2,3,4,5,6,7,8,9])
q5_arr[q5_arr%2==1]=-1
q5_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q6. Replace all odd numbers in arr with -1 without changing arr

Input:

`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`<br>
Desired Output:

`out`<br>
`#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])`<br>
`arr`<br>
`#>  array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`<br>

In [11]:
q6_arr=np.array([0,1,2,3,4,5,6,7,8,9])
out=np.array(q6_arr)

out[out%2==1]=-1
print(out)
print(q6_arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


Q7:Convert a 1D array to a 2D array with 2 rows

In [12]:
q7_arr=np.arange(10)
q7_arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q8: How to stack two arrays vertically?

Input
```
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

Output:
```
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
```

In [17]:
q8_arr_a=np.arange(10).reshape(2,-1)
q8_arr_b=np.repeat(1,10).reshape(2,-1)

In [21]:
res=np.concatenate((q8_arr_a,q8_arr_b),axis=0)

In [22]:
res

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q9: How to stack two arrays horizontally?

In [27]:
q9_arr_a=np.arange(10).reshape(2,-1)
q9_arr_b=np.repeat(1,10).reshape(2,-1)
res2=np.concatenate((q9_arr_a,q9_arr_b),axis=1)
res2

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q10. How to generate custom sequences in numpy without hardcoding?

Input:
`a = np.array([1,2,3])`

Desired Output:
`#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [31]:
q10_arr=np.array([1,2,3])
q10_output=np.concatenate((np.repeat(q10_arr,3),q10_arr,q10_arr),axis=0)
q10_output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3])

Sol2-Optimal Solution

In [32]:
q10_output=np.concatenate((np.repeat(q10_arr,3),np.tile(q10_arr,3)))
q10_output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q11: Get the common items between a and b

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Desired Output:
```
array([2, 4])
```

In [33]:
q11_arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
q11_arr_b = np.array([7,2,10,2,7,4,9,4,9,8])

In [35]:
res=np.intersect1d(q11_arr_a,q11_arr_b)

In [36]:
res

array([2, 4])

Q12: From array a remove all items present in array b

Input:
```
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
```

Desired Output:
```
array([1,2,3,4])
```

In [37]:
q12_arr_a = np.array([1,2,3,4,5])
q12_arr_b = np.array([5,6,7,8,9])

res=np.setdiff1d(q12_arr_a,q12_arr_b)

res

array([1, 2, 3, 4])

Q13: Get the positions where elements of a \and b match

Input:
```
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

Desired Output:
```
#> (array([1, 3, 5, 7]),)
```

In [40]:
q13_arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
q13_arr_b = np.array([7,2,10,2,7,4,9,4,9,8])
res=np.where(q13_arr_a==q13_arr_b)

In [41]:
res

(array([1, 3, 5, 7], dtype=int64),)

Q14: Get all items between 5 and 10 from a.

Input:
```
a = np.array([2, 6, 1, 9, 10, 3, 27])
```

Desired Output:
```
(array([6, 9, 10]),)
```

In [46]:
q14_arr=np.array([2, 6, 1, 9, 10, 3, 27])
res=q14_arr[(q14_arr>=5)&(q14_arr<=10)]
res

array([ 6,  9, 10])

Q15: Convert the function maxx that works on two scalars, to work on two arrays.

Input:
```
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
```

Desired Output:
```
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
```

In [47]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

q15_arr_a=np.array([5, 7, 9, 8, 6, 4, 5])
q15_arr_b=np.array([6, 3, 4, 8, 9, 7, 1])

vfunc=np.vectorize(maxx,otypes=[float])
res=vfunc(q15_arr_a,q15_arr_b)
res

array([6., 7., 9., 8., 9., 7., 5.])

Q16: Swap columns 1 and 2 in the array arr.

```
arr = np.arange(9).reshape(3,3)
arr
```

In [53]:
q16_arr=np.arange(9).reshape(3,3)
q16_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
q16_arr=q16_arr[:,[1,0,2]]

In [55]:
q16_arr

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])