In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5,6])

In [4]:
arr2=np.array([1,2,3,4,5])

In [5]:
arr2.shape

(5,)

In [6]:
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [7]:
arr1.shape

(6,)

In [8]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
type(arr2)

numpy.ndarray

In [11]:
type(arr2[0])

numpy.int32

In [15]:
arr=np.array([[1,2,3,4],[5,6,7,8,]])

In [16]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])